//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourfinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking1
    {
        public System.DateTime Booking_Date { get; set; }
        public string Booking_Number { get; set; }
        public Nullable<int> Number_of_Travellers { get; set; }
        public string Type_of_Booking { get; set; }
        public string Package_Booked { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> DestinationID { get; set; }
    }
}
