//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourfinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DestinationDetail()
        {
            this.Bookings1 = new HashSet<Booking1>();
        }
    
        public int DestinationID { get; set; }
        public string DestinationName { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string ImageURL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking1> Bookings1 { get; set; }
    }
}
