//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tourfinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverUser
    {
        public int UserID { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<int> DestinationID { get; set; }
        public string VehicleModel { get; set; }
    }
}
